module Lang
end

require_relative 'lang/lexeme'
require_relative 'lang/token'
require_relative 'lang/tokens'
require_relative 'lang/tokenizer'
require_relative 'lang/grammar/base'
require_relative 'lang/grammar/number'
require_relative 'lang/grammar/string'
require_relative 'lang/grammar/expression_list'
require_relative 'lang/grammar/array'
require_relative 'lang/grammar/call'
require_relative 'lang/grammar/expression'
require_relative 'lang/node/number'
require_relative 'lang/node/string'
require_relative 'lang/node/array'
require_relative 'lang/node/call'
require_relative 'lang/parser'
require_relative 'lang/stream/text'
require_relative 'lang/stream/token'
require_relative 'lang/environment'
